// Web Crypto API utilities for client-side AES-256-GCM note encryption.
//
// Architecture (single-layer envelope):
//   - generateEncryptionCode() generates a random 4-word code, shown once and
//     never stored anywhere — not even encrypted.
//   - A random data key encrypts notes; it is wrapped with PBKDF2(code) and
//     that wrapped form is what actually lives in the DB.
//   - The code is deliberately NOT wrapped under the login password or
//     stored in any recoverable form — the code is the only secret that can
//     ever unwrap the data key. A previous version also wrapped the code
//     under the password as a convenience so login alone could unlock notes;
//     that meant a compromised login password was enough to read every note
//     without ever knowing the code, defeating the point of having a
//     separate secret. There is no recovery path if the code is lost — that
//     is the intended trade-off of the code being the only thing that works.
//   - The DB stores only ciphertext; the data key only ever lives in browser memory.

const PBKDF2_ITERATIONS = 310_000; // OWASP-recommended minimum for SHA-256

export function toBase64(buf: ArrayBuffer): string {
  let binary = "";
  const bytes = new Uint8Array(buf);
  for (let i = 0; i < bytes.byteLength; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary);
}

export function fromBase64(s: string): Uint8Array {
  return new Uint8Array(
    atob(s)
      .split("")
      .map((c) => c.charCodeAt(0)),
  );
}

export function generateSalt(): Uint8Array {
  return crypto.getRandomValues(new Uint8Array(16));
}

// 256 words → 4 picks → 256^4 ≈ 2^32 combinations; PBKDF2 makes brute-force infeasible.
const WORD_LIST = [
  "able",
  "acid",
  "aged",
  "also",
  "area",
  "army",
  "away",
  "baby",
  "back",
  "ball",
  "band",
  "bank",
  "base",
  "bath",
  "bear",
  "beat",
  "been",
  "bell",
  "best",
  "bird",
  "bite",
  "blue",
  "boat",
  "body",
  "bold",
  "bond",
  "bone",
  "book",
  "bore",
  "born",
  "both",
  "bowl",
  "burn",
  "bush",
  "busy",
  "calm",
  "came",
  "camp",
  "card",
  "care",
  "cart",
  "case",
  "cash",
  "cave",
  "cell",
  "chat",
  "chip",
  "city",
  "clam",
  "clay",
  "clip",
  "club",
  "coal",
  "coat",
  "code",
  "coil",
  "coin",
  "cold",
  "cone",
  "cook",
  "cool",
  "cope",
  "copy",
  "cord",
  "core",
  "corn",
  "cost",
  "cove",
  "crew",
  "crop",
  "cure",
  "curl",
  "cute",
  "dark",
  "data",
  "dawn",
  "days",
  "dead",
  "deal",
  "dear",
  "deck",
  "deep",
  "deer",
  "deny",
  "desk",
  "dial",
  "diet",
  "dirt",
  "dish",
  "disk",
  "dive",
  "dock",
  "door",
  "dose",
  "dove",
  "down",
  "draw",
  "drew",
  "drop",
  "drum",
  "dual",
  "dull",
  "dump",
  "dusk",
  "dust",
  "duty",
  "each",
  "earn",
  "ease",
  "east",
  "edge",
  "else",
  "emit",
  "even",
  "ever",
  "evil",
  "exam",
  "exit",
  "face",
  "fact",
  "fade",
  "fail",
  "fair",
  "fall",
  "fame",
  "farm",
  "fast",
  "fate",
  "feel",
  "feet",
  "fell",
  "felt",
  "fern",
  "file",
  "fill",
  "film",
  "find",
  "fine",
  "fire",
  "firm",
  "fish",
  "fist",
  "flag",
  "flat",
  "flew",
  "flip",
  "flow",
  "foam",
  "fold",
  "folk",
  "fond",
  "font",
  "ford",
  "fore",
  "fork",
  "form",
  "fort",
  "foul",
  "four",
  "free",
  "from",
  "fuel",
  "full",
  "fund",
  "fuse",
  "gale",
  "game",
  "gate",
  "gave",
  "gear",
  "gene",
  "gift",
  "girl",
  "give",
  "glad",
  "glow",
  "glue",
  "goal",
  "gold",
  "golf",
  "gone",
  "good",
  "grab",
  "gray",
  "grin",
  "grip",
  "grow",
  "gulf",
  "guru",
  "hair",
  "half",
  "hall",
  "halt",
  "hand",
  "hang",
  "hard",
  "harm",
  "harp",
  "have",
  "head",
  "heal",
  "heap",
  "heat",
  "held",
  "helm",
  "help",
  "herb",
  "here",
  "hide",
  "high",
  "hill",
  "hint",
  "hold",
  "hole",
  "home",
  "hook",
  "hope",
  "horn",
  "host",
  "hour",
  "huge",
  "hull",
  "hunt",
  "hurt",
  "idea",
  "idle",
  "inch",
  "into",
  "iron",
  "isle",
  "item",
  "join",
  "joke",
  "jump",
  "just",
  "keen",
  "kept",
  "kind",
  "king",
  "knee",
  "knew",
  "know",
  "lack",
  "lake",
  "lamp",
  "land",
  "lane",
  "last",
  "late",
  "lava",
  "lawn",
  "lead",
  "leaf",
  "lean",
  "left",
  "lens",
  "life",
  "lift",
  "like",
  "lime",
  "line",
  "link",
  "lion",
  "list",
  "live",
  "load",
  "loan",
  "lock",
  "loft",
  "lone",
  "long",
  "look",
  "loop",
  "lord",
  "lore",
  "loss",
  "lost",
  "loud",
  "love",
  "luck",
  "lung",
  "made",
  "mail",
  "main",
  "make",
  "many",
  "mark",
  "mart",
  "mast",
  "math",
  "maze",
  "meal",
  "meat",
  "meet",
  "melt",
  "mesh",
  "mild",
  "mile",
  "mill",
  "mind",
  "mine",
  "mint",
  "mist",
  "mode",
  "moon",
  "more",
  "most",
  "move",
  "much",
  "muse",
  "must",
  "nail",
  "name",
  "near",
  "neat",
  "need",
  "nest",
  "next",
  "nice",
  "nine",
  "node",
  "none",
  "noon",
  "norm",
  "nose",
  "note",
  "nova",
  "null",
  "numb",
  "oath",
  "obey",
  "odds",
  "once",
  "only",
  "open",
  "oral",
  "orb",
  "orca",
  "oval",
  "oven",
  "over",
  "oxen",
  "pace",
  "pack",
  "page",
  "paid",
  "pair",
  "palm",
  "park",
  "part",
  "pass",
  "path",
  "peak",
  "pick",
  "pier",
  "pile",
  "pine",
  "pipe",
  "plan",
  "play",
  "plot",
  "plow",
  "plug",
  "plus",
  "poem",
  "poet",
  "pole",
  "pond",
  "pool",
  "poor",
  "port",
  "pose",
  "pour",
  "prey",
  "prop",
  "pull",
  "pump",
  "pure",
  "push",
  "raid",
  "rail",
  "rain",
  "ramp",
  "rank",
  "rare",
  "rate",
  "read",
  "real",
  "reed",
  "reef",
  "reel",
  "rely",
  "rent",
  "rest",
  "rice",
  "rich",
  "ride",
  "ring",
  "rise",
  "risk",
  "road",
  "roam",
  "rock",
  "role",
  "roll",
  "roof",
  "root",
  "rope",
  "rose",
  "rove",
  "rule",
  "rush",
  "rust",
  "safe",
  "sage",
  "sail",
  "sake",
  "salt",
  "same",
  "sand",
  "save",
  "scan",
  "seal",
  "seed",
  "seep",
  "self",
  "sell",
  "send",
  "sent",
  "ship",
  "shop",
  "shot",
  "show",
  "side",
  "sign",
  "silk",
  "silo",
  "sing",
  "sink",
  "site",
  "size",
  "skin",
  "skip",
  "slab",
  "slim",
  "slip",
  "slow",
  "slug",
  "snap",
  "snow",
  "soap",
  "soft",
  "soil",
  "sold",
  "sole",
  "some",
  "song",
  "sort",
  "soul",
  "span",
  "spin",
  "spur",
  "star",
  "stay",
  "stem",
  "step",
  "stir",
  "stop",
  "strap",
  "stub",
  "suit",
  "surf",
  "swap",
  "tall",
  "tank",
  "task",
  "tell",
  "term",
  "test",
  "text",
  "than",
  "that",
  "them",
  "then",
  "tide",
  "tied",
  "tile",
  "till",
  "time",
  "tiny",
  "tire",
  "toad",
  "told",
  "tone",
  "took",
  "tool",
  "tour",
  "town",
  "trap",
  "tree",
  "trim",
  "trip",
  "true",
  "tube",
  "tune",
  "turn",
  "type",
  "unit",
  "upon",
  "used",
  "user",
  "vale",
  "vast",
  "veil",
  "vent",
  "vest",
  "view",
  "vine",
  "void",
  "volt",
  "vote",
  "wade",
  "wage",
  "wake",
  "walk",
  "wall",
  "wand",
  "ward",
  "warm",
  "warp",
  "wave",
  "weak",
  "weld",
  "well",
  "went",
  "west",
  "wide",
  "wild",
  "will",
  "wind",
  "wine",
  "wire",
  "wise",
  "wish",
  "with",
  "woke",
  "wolf",
  "wood",
  "word",
  "work",
  "worm",
  "worn",
  "wove",
  "yard",
  "year",
  "your",
  "zero",
  "zinc",
  "zone",
  "zoom",
];

export function generateEncryptionCode(): string {
  const indices = crypto.getRandomValues(new Uint8Array(4));
  return Array.from(indices)
    .map((i) => WORD_LIST[i])
    .join("-");
}

// Detects whether a field value was encrypted by encryptPII (stored as JSON {c, iv}).
export function isEncryptedValue(value: string): boolean {
  if (!value?.startsWith("{")) return false;
  try {
    const p = JSON.parse(value);
    return typeof p.c === "string" && typeof p.iv === "string";
  } catch {
    return false;
  }
}

// Derives a key-encryption-key from a password (or recovery code) and a salt.
export async function deriveKEK(secret: string, salt: Uint8Array): Promise<CryptoKey> {
  const keyMaterial = await crypto.subtle.importKey("raw", new TextEncoder().encode(secret), "PBKDF2", false, [
    "deriveKey",
  ]);
  return crypto.subtle.deriveKey(
    { name: "PBKDF2", salt, iterations: PBKDF2_ITERATIONS, hash: "SHA-256" },
    keyMaterial,
    { name: "AES-GCM", length: 256 },
    false,
    ["encrypt", "decrypt"],
  );
}

// Generates a fresh random AES-256-GCM data key.
export async function generateDataKey(): Promise<CryptoKey> {
  return crypto.subtle.generateKey({ name: "AES-GCM", length: 256 }, true, ["encrypt", "decrypt"]);
}

// Wraps (encrypts) a data key with a KEK. Returns base64-encoded iv + ciphertext.
export async function wrapDataKey(dataKey: CryptoKey, kek: CryptoKey): Promise<{ iv: string; wrapped: string }> {
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const raw = await crypto.subtle.exportKey("raw", dataKey);
  const wrapped = await crypto.subtle.encrypt({ name: "AES-GCM", iv }, kek, raw);
  return { iv: toBase64(iv), wrapped: toBase64(wrapped) };
}

// Unwraps a data key. Throws DOMException if the KEK is wrong (wrong password).
export async function unwrapDataKey(wrapped: string, iv: string, kek: CryptoKey): Promise<CryptoKey> {
  const raw = await crypto.subtle.decrypt({ name: "AES-GCM", iv: fromBase64(iv) }, kek, fromBase64(wrapped));
  return crypto.subtle.importKey("raw", raw, { name: "AES-GCM", length: 256 }, true, ["encrypt", "decrypt"]);
}

// Encrypts a note string. Each call generates a fresh random IV.
export async function encryptNote(content: string, dataKey: CryptoKey): Promise<{ iv: string; ciphertext: string }> {
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const ciphertext = await crypto.subtle.encrypt({ name: "AES-GCM", iv }, dataKey, new TextEncoder().encode(content));
  return { iv: toBase64(iv), ciphertext: toBase64(ciphertext) };
}

// Decrypts a note given its ciphertext and per-note IV.
export async function decryptNote(ciphertext: string, iv: string, dataKey: CryptoKey): Promise<string> {
  const raw = await crypto.subtle.decrypt({ name: "AES-GCM", iv: fromBase64(iv) }, dataKey, fromBase64(ciphertext));
  return new TextDecoder().decode(raw);
}
