import { useEffect, useRef, useState } from "react";

import type { Dayjs } from "dayjs";
import dayjs from "dayjs";

import Button from "@components/shared/Button/Button";
import ConfirmModal from "@components/shared/ConfirmModal/ConfirmModal";
import DateInput from "@components/shared/DateInput/DateInput";
import InfoTooltip from "@components/shared/InfoTooltip/InfoTooltip";
import Lookup from "@components/shared/Lookup/Lookup";
import Modal from "@components/shared/Modal/Modal";

import { useAuth } from "@/context/AuthContext";
import { useToast } from "@/context/ToastContext";
import { useWarnOnDirtyUnload } from "@/Hooks/useWarnOnDirtyUnload";
import { supabase } from "@/lib/supabase.js";
import { Session } from "@/models/globalTypes";
import { useAppDispatch, useAppSelector, useFetchOnIdle } from "@/store/hooks";
import { fetchPracticeSettings } from "@/store/slices/practiceSettingsSlice";
import { createSession, updateSession } from "@/store/slices/sessionsSlice";

import styles from "./CreateSessionModal.module.scss";

// Deep-links to the Billing tab and scrolls the "Session types & prices"
// card into view (see SettingsCard's `id`/`?section=` handling).
const SESSION_TYPES_SETTINGS_URL = "/settings?tab=billing&section=packages";

// Same snake_case, feature-prefixed, try/catch-guarded localStorage pattern
// as ViewportWarningBanner/MessagingNotice — shows the "here's how this
// works" intro once per browser, never again after Get started is clicked.
const CREATE_SESSION_INTRO_KEY = "create_session_modal_intro_seen";
function readIntroSeen(): boolean {
  try {
    return window.localStorage.getItem(CREATE_SESSION_INTRO_KEY) === "true";
  } catch {
    return false;
  }
}

export type StubSavePayload = {
  dates: string[];
  duration_minutes: number;
  price_pence: number;
  paid: boolean;
  address: string;
  notes: string;
  reference_code: string;
};

type CreateSessionModalTypes = {
  clientId?: string;
  clientName?: string;
  onClose: () => void;
  session?: Session | null;
  onSave?: (payload: StubSavePayload) => Promise<void>;
  // Pre-fill the date/time field for a brand-new session (e.g. the admin
  // scheduler's click-an-empty-slot flow). Ignored when editing an existing one.
  initialStart?: Dayjs | null;
  // Agency clients only: when set, the fee is pinned to this amount and the
  // field is read-only — the agency set this client's rate and didn't opt
  // the assigned staff member out of it (client_stubs.allow_staff_custom_rate).
  lockedPricePence?: number | null;
};

const CreateSessionModal = ({
  clientId,
  onClose,
  clientName,
  session = null,
  onSave,
  initialStart = null,
  lockedPricePence = null,
}: CreateSessionModalTypes) => {
  const { authUser, isDemo } = useAuth();
  const { showToast } = useToast();
  const dispatch = useAppDispatch();
  const [scheduledAt, setScheduledAt] = useState<Dayjs | null>(() => {
    if (!session) return initialStart;
    // Never seed the picker with an unparseable date — MUI then falls back to
    // its 1900 minDate, which is how an edited session once ended up dated 1900.
    const parsed = dayjs(session.scheduled_at);
    return parsed.isValid() ? parsed : (initialStart ?? dayjs());
  });

  const [isSaving, setIsSaving] = useState(false);
  // Whether the picked session type is a recurring block, and how many
  // sessions it contains. Both are driven entirely by the selected type in
  // Settings — there's no manual "recurring" toggle any more.
  const [isRecurring, setIsRecurring] = useState(false);
  const [sessionCount, setSessionCount] = useState(1);
  const [sessionDuration, setSessionDuration] = useState(session?.duration_minutes ?? 50);
  const [isPrepaid, setIsPrepaid] = useState(session?.paid ?? false);
  const [pricePounds, setPricePounds] = useState(() => {
    if (lockedPricePence != null) return (lockedPricePence / 100).toFixed(2);
    return session?.price_pence ? (session.price_pence / 100).toFixed(2) : "60.00";
  });
  const [location, setLocation] = useState<"remote" | "in_person">(session?.location ?? "in_person");
  const [sessionAddress, setSessionAddress] = useState(session?.address ?? "");
  const [notes, setNotes] = useState(session?.notes ?? "");
  const [referenceCode, setReferenceCode] = useState(session?.reference_code ?? "");
  // Tracks whether the current reference code was generated by us (block
  // auto-fill) rather than typed by the admin, so picking a different
  // session type can safely replace/clear it without ever clobbering
  // something the admin actually typed themselves.
  const [referenceCodeAutoFilled, setReferenceCodeAutoFilled] = useState(false);
  const [sendConfirmation, setSendConfirmation] = useState(true);
  const [sendReminders, setSendReminders] = useState(true);
  const [sendRescheduleNotification, setSendRescheduleNotification] = useState(true);
  const [error, setError] = useState("");
  const [savedLocations, setSavedLocations] = useState<string[]>([]);
  const [savingLocation, setSavingLocation] = useState(false);
  const [sessionPackages, setSessionPackages] = useState<
    {
      id: string;
      name: string;
      price_pence: number;
      duration_minutes: number;
      is_recurring: boolean;
      session_count: number;
    }[]
  >([]);
  const [selectedPackageId, setSelectedPackageId] = useState("");
  const [showDiscardConfirm, setShowDiscardConfirm] = useState(false);
  // Only for the create flow (never editing an existing session) — a first
  // booking benefits from knowing it's 3 short steps before diving into
  // fields; editing is a single quick change, not worth interrupting.
  const [showIntro, setShowIntro] = useState(() => !session && !readIntroSeen());
  const dismissIntro = () => {
    try {
      window.localStorage.setItem(CREATE_SESSION_INTRO_KEY, "true");
    } catch {
      // Storage disabled/unavailable — just don't persist; showing the intro
      // again next time is a minor inconvenience, not worth surfacing.
    }
    setShowIntro(false);
  };

  // Cheap dirty-check: snapshot every field once on mount (already reflecting
  // whatever session/initialStart pre-filled it with), then compare against
  // that snapshot on every render. Only real edits — not the modal's own
  // defaults — trip it, so a freshly opened blank "create" modal is never
  // treated as dirty just because pricePounds defaults to "60.00".
  const getFieldSnapshot = () =>
    JSON.stringify({
      scheduledAt: scheduledAt?.toISOString() ?? null,
      selectedPackageId,
      sessionDuration,
      pricePounds,
      isPrepaid,
      location,
      sessionAddress,
      notes,
      referenceCode,
      sendConfirmation,
      sendReminders,
      sendRescheduleNotification,
    });
  const initialSnapshotRef = useRef(getFieldSnapshot());
  const isDirty = getFieldSnapshot() !== initialSnapshotRef.current;
  useWarnOnDirtyUnload(isDirty);

  const requestClose = () => {
    if (isDirty) {
      setShowDiscardConfirm(true);
    } else {
      onClose();
    }
  };

  useFetchOnIdle((state) => state.practiceSettings.status, fetchPracticeSettings, "Failed to load practice settings");
  const cachedSavedLocations = useAppSelector((state) => state.practiceSettings.data?.saved_locations);
  useEffect(() => {
    if (cachedSavedLocations) setSavedLocations(cachedSavedLocations as string[]);
  }, [cachedSavedLocations]);

  // Session types configured in Settings — picking one just prefills duration
  // and price below; both stay freely editable after, since not every booking
  // fits a preset (sliding scale, one-off rate, etc).
  useEffect(() => {
    if (!authUser?.id) return;
    supabase
      .from("session_packages")
      .select("id, name, price_pence, duration_minutes, is_recurring, session_count")
      .eq("admin_id", authUser.id)
      .eq("archived", false)
      .order("sort_order")
      .then(({ data }) => {
        if (data) setSessionPackages(data);
      });
  }, [authUser?.id]);

  const handleSelectPackage = (id: string) => {
    setSelectedPackageId(id);
    const pkg = sessionPackages.find((p) => p.id === id);
    if (!pkg) {
      // "Custom — set below": a hand-priced one-off, never a block.
      setIsRecurring(false);
      setSessionCount(1);
      if (referenceCodeAutoFilled) {
        setReferenceCode("");
        setReferenceCodeAutoFilled(false);
      }
      return;
    }
    setSessionDuration(pkg.duration_minutes);
    // For a recurring type, price_pence is the whole-block price. The field
    // below shows it as such; handleSave divides it across the rows. Never
    // when the agency has locked this client's rate — a package pick
    // shouldn't be a backdoor around it.
    if (lockedPricePence == null) setPricePounds((pkg.price_pence / 100).toFixed(2));
    setIsRecurring(pkg.is_recurring);
    setSessionCount(pkg.is_recurring ? pkg.session_count : 1);

    // handleSave stamps this same reference_code onto every session in the
    // block, so auto-filling one here is what actually makes the field a
    // shared block reference rather than something the admin has to
    // remember to type themselves. Only touches the field when it's empty
    // or still holding a code we generated — never overwrites something
    // the admin typed by hand.
    if (pkg.is_recurring && !session) {
      if (!referenceCode || referenceCodeAutoFilled) {
        setReferenceCode(`BLK-${crypto.randomUUID().slice(0, 6).toUpperCase()}`);
        setReferenceCodeAutoFilled(true);
      }
    } else if (referenceCodeAutoFilled) {
      setReferenceCode("");
      setReferenceCodeAutoFilled(false);
    }
  };

  const handleSaveLocation = async () => {
    if (!sessionAddress.trim() || !authUser) return;
    const updated = [...new Set([...savedLocations, sessionAddress.trim()])];
    setSavingLocation(true);
    const { error } = await supabase
      .from("practice_settings")
      .update({ saved_locations: updated })
      .eq("admin_id", authUser.id);
    if (!error) setSavedLocations(updated);
    setSavingLocation(false);
  };

  const handleRemoveLocation = async (loc: string) => {
    if (!authUser) return;
    const updated = savedLocations.filter((l) => l !== loc);
    await supabase.from("practice_settings").update({ saved_locations: updated }).eq("admin_id", authUser.id);
    setSavedLocations(updated);
  };

  // Server-side overlap check. The single source of truth is the DB
  // (`practice_slot_has_conflict` + the prevent_*_double_booking triggers): it
  // sees BOTH real sessions and offline-client (stub) sessions, and isn't
  // limited to whatever slice of `state.sessions` this page happens to hold.
  // Returns an error message for the first clashing date, or null when clear.
  const firstOverlappingDate = async (
    candidates: Dayjs[],
    excludeSessionId: string | null,
    excludeStubSessionId: string | null,
  ): Promise<string | null> => {
    if (!authUser) return null;
    for (const d of candidates) {
      const { data: clash, error: rpcError } = await supabase.rpc("practice_slot_has_conflict", {
        p_admin_id: authUser.id,
        p_start: d.toISOString(),
        p_duration_minutes: sessionDuration,
        p_exclude_session_id: excludeSessionId,
        p_exclude_stub_session_id: excludeStubSessionId,
      });
      // Fail open on a transient RPC error — the DB trigger still blocks the write.
      if (rpcError) continue;
      if (clash) return `${d.format("D MMM [at] h:mma")} overlaps with an existing session.`;
    }
    return null;
  };

  const handleSave = async () => {
    if (isDemo) {
      showToast("Demo mode — changes are not saved.");
      onClose();
      return;
    }
    if (!authUser || !scheduledAt || !scheduledAt.isValid()) return;
    setIsSaving(true);
    setError("");

    const dates = [scheduledAt];
    if (isRecurring) {
      for (let i = 1; i < sessionCount; i++) {
        dates.push(scheduledAt.add(i, "week"));
      }
    }

    // Block double booking before any inserts — covers the stub (`onSave`) path too.
    const overlapError = await firstOverlappingDate(dates, null, null);
    if (overlapError) {
      setError(overlapError);
      showToast(overlapError, "danger");
      setIsSaving(false);
      return;
    }

    // For a recurring block the fee field holds the WHOLE-BLOCK price. Split
    // it evenly across the rows so each session carries its own per-session
    // fee and the block still sums to the total — create-checkout-session
    // sums price_pence across a block, so an undivided price would overcharge
    // by a factor of N. Any rounding remainder lands on the first session.
    const totalPence = pricePounds ? Math.round(parseFloat(pricePounds) * 100) : 0;
    const n = dates.length;
    const perSessionPence = Math.floor(totalPence / n);
    const priceForIndex = (i: number) => (i === 0 ? totalPence - perSessionPence * (n - 1) : perSessionPence);

    if (onSave) {
      try {
        await onSave({
          dates: dates.map((d) => d.toISOString()),
          duration_minutes: sessionDuration,
          price_pence: n > 1 ? Math.round(totalPence / n) : totalPence,
          paid: isPrepaid,
          address: sessionAddress,
          notes: notes.trim(),
          reference_code: referenceCode.trim(),
        });
      } catch (err: any) {
        const raw = err?.message || String(err);
        const text = /overlap/i.test(raw)
          ? "That time overlaps with another session — pick a different time."
          : raw || "Failed to save session.";
        setError(text);
        showToast(text, "danger");
      }
      setIsSaving(false);
      return;
    }

    // For batch creates, tag every session with a shared block_id so the
    // counsellor can see "Block 15 Jan · 2/4" on each card and track cadence.
    const blockId = isRecurring ? crypto.randomUUID().slice(0, 6) : null;

    const result = await Promise.all(
      dates.map((date, i) =>
        dispatch(
          createSession({
            client_id: clientId,
            scheduled_at: date.toISOString(),
            paid: isPrepaid,
            price_pence: priceForIndex(i),
            duration_minutes: sessionDuration,
            notes: notes.trim() || undefined,
            reference_code: referenceCode.trim() || undefined,
            location: location,
            address: sessionAddress,
            send_reminders: sendReminders,
            created_by: authUser.id,
            metadata: sessionPackages
              ? {
                  block_id: blockId,
                  block_pos: i + 1,
                  block_total: dates.length,
                  block_start: scheduledAt.toISOString(),
                  block_price_pence: totalPence,
                }
              : undefined,
          }),
        ),
      ),
    );

    const allSuccess = result.every((i) => i?.meta.requestStatus === "fulfilled");

    if (allSuccess) {
      let emailNote = "";
      if (sendConfirmation) {
        // One email for the whole block, not one per session. Awaited so the
        // toast reflects what actually happened rather than always claiming the
        // email went out.
        const ids = result.filter((r) => r?.meta.requestStatus === "fulfilled").map((r) => (r.payload as Session).id);
        let send: ReturnType<typeof supabase.functions.invoke> | null = null;
        if (blockId && ids.length > 1) {
          send = supabase.functions.invoke("notify-block-booked", { body: { session_ids: ids } });
        } else if (ids[0]) {
          send = supabase.functions.invoke("notify-session-booked", { body: { session_id: ids[0] } });
        }
        if (send) {
          const res = await send.catch((e) => ({ error: e }));
          emailNote = res.error ? " — but the confirmation email couldn't be sent" : " — confirmation email sent";
        }
      }
      showToast(`${dates.length > 1 ? `${dates.length} sessions` : "Session"} scheduled${emailNote}.`, "success");
      onClose();
    } else {
      const overlap = result.some((r) => /overlap/i.test(String(r?.payload ?? "")));
      const text = overlap
        ? "That time overlaps with another session — pick a different time."
        : "Failed to schedule session. Please try again.";
      setError(text);
      showToast(text, "danger");
    }
    setIsSaving(false);
  };

  const handleSessionUpdate = async (sess: Session) => {
    if (isDemo) {
      showToast("Demo mode — changes are not saved.");
      onClose();
      return;
    }

    if (!authUser || !scheduledAt || !scheduledAt.isValid()) return;
    setError("");
    setIsSaving(true);

    // Exclude the row being edited — a stub when `onSave` is set (its id lives in
    // stub_sessions), otherwise a real session.
    const overlapError = await firstOverlappingDate([scheduledAt], onSave ? null : sess.id, onSave ? sess.id : null);
    if (overlapError) {
      setError(overlapError);
      showToast(overlapError, "danger");
      setIsSaving(false);
      return;
    }

    if (onSave) {
      try {
        await onSave({
          dates: [scheduledAt.toISOString()],
          duration_minutes: sessionDuration,
          price_pence: pricePounds ? Math.round(parseFloat(pricePounds) * 100) : 0,
          paid: isPrepaid,
          address: sessionAddress,
          notes: notes.trim(),
          reference_code: referenceCode.trim(),
        });
        onClose();
      } catch (err: any) {
        const raw = err?.message || String(err);
        const text = /overlap/i.test(raw)
          ? "That time overlaps with another session — pick a different time."
          : raw || "Failed to update session.";
        setError(text);
        showToast(text, "danger");
      }
      setIsSaving(false);
      return;
    }

    try {
      await dispatch(
        updateSession({
          id: sess.id,
          paid: isPrepaid,
          price_pence: pricePounds ? Math.round(parseFloat(pricePounds) * 100) : 0,
          notes: notes.trim() || null,
          reference_code: referenceCode.trim() || null,
          scheduled_at: scheduledAt.toISOString(),
          duration_minutes: sessionDuration,
          location: location,
          address: sessionAddress,
          status: "rescheduled",
        }),
      ).unwrap();
      if (sendRescheduleNotification) {
        supabase.functions.invoke("notify-session-rescheduled", {
          body: { session_id: sess.id, previous_date: sess.scheduled_at },
        });
      }
      onClose();
      setIsSaving(false);
      showToast("Session updated successfully.", "success");
    } catch (err: any) {
      const message = err?.message || String(err) || "oops";
      const text = /overlap/i.test(message)
        ? "That time overlaps with another session — pick a different time."
        : `Something went wrong: ${message}`;
      setError(text);
      showToast(text, "danger");
    }
  };

  // The stub-save (offline client) flow has no email-notification concept —
  // the Confirm step below just skips those checkboxes for it, same 3 steps.
  const showNotifyStep = !onSave;
  const STEP_LABELS = ["Date & location", "Session & fee", "Confirm"];
  const [step, setStep] = useState(0);
  const lastStep = STEP_LABELS.length - 1;

  const dateStepValid = !!scheduledAt && scheduledAt.isValid();
  const feeStepValid =
    sessionDuration > 0 &&
    pricePounds.trim() !== "" &&
    !Number.isNaN(parseFloat(pricePounds)) &&
    parseFloat(pricePounds) >= 0;
  // The reason THIS step's Next is blocked, or "" when it isn't. Next used to
  // just silently no-op when a required field was missing — same disabled
  // state, zero explanation, which reads as broken rather than "fill this
  // in first". Surfacing it through the same error slot save failures use
  // means clicking Next always does *something* visible.
  let stepBlockedReason = "";
  if (step === 0 && !dateStepValid) stepBlockedReason = "Pick a date & time to continue.";
  if (step === 1 && !feeStepValid) stepBlockedReason = "Enter a duration and fee to continue.";

  const goNext = () => {
    if (stepBlockedReason) {
      setError(stepBlockedReason);
      return;
    }
    setError("");
    setStep((s) => Math.min(s + 1, lastStep));
  };
  const goBack = () => {
    setError("");
    setStep((s) => Math.max(s - 1, 0));
  };

  const selectedPackage = sessionPackages.find((p) => p.id === selectedPackageId) ?? null;

  const dynamicNewSessionModal = () => {
    if (showIntro) {
      return (
        <Modal
          title={`Create session - ${clientName}`}
          onClose={requestClose}
          size="sm"
          actions={
            <div className={styles.modalActions}>
              <Button variant="ghost" onClick={requestClose}>
                Cancel
              </Button>
              <Button onClick={dismissIntro}>Get started</Button>
            </div>
          }
        >
          <div className={styles.form}>
            <h3 className={styles.stepHeading}>Booking a session takes 3 quick steps</h3>
            <ol className={styles.introList}>
              <li>
                <strong>Date & location</strong> — when it's happening, and where.
              </li>
              <li>
                <strong>Session & fee</strong> — pick a session type (or set your own) and duration.
              </li>
              <li>
                <strong>Confirm</strong> — payment status, notes, and whether to email the client.
              </li>
            </ol>
            <p className={styles.hint}>This only shows once — you can jump straight in next time.</p>
          </div>
        </Modal>
      );
    }

    let primaryAction: React.ReactNode;
    if (step < lastStep) {
      primaryAction = <Button onClick={goNext}>Next</Button>;
    } else if (session) {
      primaryAction = (
        <Button onClick={() => handleSessionUpdate(session)} disabled={!scheduledAt?.isValid() || isSaving}>
          {isSaving ? "Updating session..." : "Update session"}
        </Button>
      );
    } else {
      primaryAction = (
        <Button onClick={handleSave} disabled={!scheduledAt?.isValid() || isSaving}>
          {/** biome-ignore lint/style/noNestedTernary: label depends on both save-in-flight and block-vs-single state */}
          {isSaving ? "Scheduling…" : isRecurring ? "Schedule sessions" : "Schedule session"}
        </Button>
      );
    }

    return (
      <Modal
        title={session ? "Update session" : `Create session - ${clientName}`}
        onClose={requestClose}
        size="sm"
        actions={
          <div className={styles.modalActions}>
            <Button variant="ghost" onClick={requestClose}>
              Cancel
            </Button>
            <div className={styles.mainActions}>
              {step > 0 && (
                <Button variant="ghost" onClick={goBack}>
                  Back
                </Button>
              )}

              {primaryAction}
            </div>
          </div>
        }
      >
        <div className={styles.form}>
          {STEP_LABELS.length > 1 && (
            <>
              <div className={styles.stepDots} aria-label={`Step ${step + 1} of ${STEP_LABELS.length}`}>
                {STEP_LABELS.map((label, i) => (
                  <div key={label} className={`${styles.stepDot} ${step >= i ? styles.stepDotActive : ""}`} />
                ))}
              </div>
              <h3 className={styles.stepHeading}>{STEP_LABELS[step]}</h3>
            </>
          )}

          {step === 0 && (
            <>
              <fieldset className={styles.fieldGroup}>
                <legend className={styles.label}>Date & time</legend>
                <DateInput mode="datetime" value={scheduledAt} onChange={setScheduledAt} />
                {!dateStepValid && <p className={styles.hint}>Pick a date & time to continue.</p>}
              </fieldset>

              <fieldset className={styles.fieldGroup}>
                <legend className={styles.label}>Session location</legend>
                <div className={styles.locationRadios}>
                  <label className={styles.radioLabel}>
                    <input
                      type="radio"
                      name="sessionLocation"
                      checked={location === "in_person"}
                      onChange={() => setLocation("in_person")}
                    />
                    In-person
                  </label>
                  <label className={styles.radioLabel}>
                    <input
                      type="radio"
                      name="sessionLocation"
                      checked={location === "remote"}
                      onChange={() => setLocation("remote")}
                    />
                    Remote
                  </label>
                </div>
                {location === "in_person" ? (
                  <Lookup
                    value={sessionAddress}
                    onChange={setSessionAddress}
                    options={savedLocations}
                    onSave={handleSaveLocation}
                    onRemove={handleRemoveLocation}
                    saving={savingLocation}
                    saveLabel="+ Save this location"
                    placeholder="e.g. 15 London Rd, LD5 4EO (optional)"
                  />
                ) : (
                  <input
                    className={styles.input}
                    type="url"
                    placeholder="Meeting link (optional)"
                    value={sessionAddress}
                    onChange={(e) => setSessionAddress(e.target.value)}
                  />
                )}
              </fieldset>
            </>
          )}

          {step === 1 && (
            <>
              {sessionPackages.length > 0 ? (
                <fieldset className={styles.fieldGroup}>
                  <legend className={styles.label}>
                    Session type
                    <InfoTooltip
                      variant="rich"
                      title="Session types"
                      text={
                        "Presets you set up once in Settings → Billing & payments → Session types & prices.\n" +
                        "Picking one fills in the price and duration below — everything stays editable.\n" +
                        "A recurring block creates several weekly sessions in one step, starting from the date above. The block price is split evenly across them and paid for as a unit."
                      }
                    />
                  </legend>
                  <div className={styles.inputWrapper}>
                    <select
                      id="session-package"
                      className={styles.input}
                      value={selectedPackageId}
                      onChange={(e) => handleSelectPackage(e.target.value)}
                    >
                      <option value="">Custom — set below</option>
                      {sessionPackages.map((p) => (
                        <option key={p.id} value={p.id}>
                          {p.name} — £{(p.price_pence / 100).toFixed(2)}
                          {p.is_recurring ? ` · ${p.session_count}-week block` : ""} · {p.duration_minutes}
                        </option>
                      ))}
                    </select>
                  </div>
                  {selectedPackage && (
                    <p className={styles.hint}>
                      {selectedPackage.is_recurring
                        ? `Creates ${selectedPackage.session_count} weekly sessions of ${selectedPackage.duration_minutes} min, £${(selectedPackage.price_pence / 100).toFixed(2)} total.`
                        : `${selectedPackage.duration_minutes} min · £${(selectedPackage.price_pence / 100).toFixed(2)}.`}
                    </p>
                  )}
                  <a className={styles.settingsLink} href={SESSION_TYPES_SETTINGS_URL} target="_blank" rel="noreferrer">
                    Manage session types →
                  </a>
                </fieldset>
              ) : (
                !session && (
                  <p className={styles.hint}>
                    Tip: save your usual prices and durations as{" "}
                    <a
                      className={styles.settingsLink}
                      href={SESSION_TYPES_SETTINGS_URL}
                      target="_blank"
                      rel="noreferrer"
                    >
                      session types in Settings
                    </a>{" "}
                    — including recurring blocks — so you can pick them here instead of retyping.
                  </p>
                )
              )}

              <fieldset className={styles.fieldGroup}>
                <legend className={styles.label}>Session duration</legend>
                <div className={styles.inputWrapper}>
                  <input
                    id="session-duration"
                    className={styles.input}
                    type="number"
                    min={10}
                    max={90}
                    value={sessionDuration}
                    onChange={(e) => setSessionDuration(Number(e.target.value))}
                  />
                </div>
              </fieldset>

              <div className={styles.fieldGroup}>
                <legend className={styles.label}>
                  {isRecurring && !session ? `Block fee (£) — covers ${sessionCount} sessions` : "Session fee (£)"}
                  <InfoTooltip
                    variant="rich"
                    title="Session Fee information"
                    text={`Creates ${sessionCount} sessions, one week apart starting from the date above.
                They're tracked and paid together — marking any one of them as paid marks the whole block as paid.`}
                  />
                </legend>

                <input
                  id="session-price"
                  className={styles.input}
                  type="number"
                  min={0}
                  step={0.01}
                  placeholder="e.g. 70.00"
                  value={pricePounds}
                  // readOnly alone doesn't reliably block a number input's
                  // native spinner arrows in every browser engine — guard
                  // the state update itself so a locked rate can't be nudged
                  // via the spinner even if the attribute is bypassed.
                  onChange={(e) => {
                    if (lockedPricePence == null) setPricePounds(e.target.value);
                  }}
                  readOnly={lockedPricePence != null}
                  title={lockedPricePence != null ? "Set by your agency — you can't change this" : undefined}
                />
                {lockedPricePence != null && (
                  <p className={styles.hint}>Set by your agency for this client — you can't charge a different rate.</p>
                )}
                {isRecurring && !session && pricePounds && sessionCount > 1 && (
                  <p className={styles.hint} data-testid="per-session-fee">
                    The client pays this once for the whole block. Each session shows £
                    {(parseFloat(pricePounds) / sessionCount).toFixed(2)}.
                  </p>
                )}
                {!feeStepValid && <p className={styles.hint}>Enter a duration and fee to continue.</p>}
              </div>
            </>
          )}

          {step === 2 && (
            <>
              <fieldset className={styles.fieldGroup}>
                <legend className={styles.label}>Payment</legend>
                <div className={styles.radioGroup}>
                  <label className={styles.radioLabel}>
                    <input type="radio" name="payment" checked={!isPrepaid} onChange={() => setIsPrepaid(false)} />
                    Payment pending
                  </label>
                  <label className={styles.radioLabel}>
                    <input type="radio" name="payment" checked={isPrepaid} onChange={() => setIsPrepaid(true)} />
                    Prepaid
                  </label>
                </div>
              </fieldset>

              <div className={styles.fieldGroup}>
                <label className={styles.label} htmlFor="session-notes">
                  Notes <span className={styles.optional}>(optional)</span>
                </label>
                <textarea
                  id="session-notes"
                  className={styles.textarea}
                  placeholder="Any prep notes or context for this session…"
                  rows={3}
                  value={notes}
                  onChange={(e) => setNotes(e.target.value)}
                />
              </div>

              <div className={styles.fieldGroup}>
                <label className={styles.label} htmlFor="session-code">
                  Reference code <span className={styles.optional}>(optional)</span>
                  <InfoTooltip
                    variant="rich"
                    title="Reference code"
                    text={
                      "Your own free-text tag for this session — an invoice number, case ref, anything you file it under.\n" +
                      "Booking a recurring block auto-fills one shared code across every session in it, so they're easy to match up later — edit or clear it any time, and typing your own replaces it."
                    }
                  />
                </label>
                <input
                  id="session-code"
                  className={styles.input}
                  type="text"
                  placeholder="e.g. S-001"
                  maxLength={20}
                  value={referenceCode}
                  onChange={(e) => {
                    setReferenceCode(e.target.value);
                    setReferenceCodeAutoFilled(false);
                  }}
                />
              </div>
            </>
          )}

          {step === 2 && showNotifyStep && !session && (
            <fieldset className={styles.fieldGroup}>
              <legend className={styles.label}>Email notifications</legend>
              <div className={styles.checkboxGroup}>
                <input
                  id="send-confirmation"
                  type="checkbox"
                  checked={sendConfirmation}
                  onChange={(e) => setSendConfirmation(e.target.checked)}
                />
                <label htmlFor="send-confirmation" className={styles.checkboxLabel}>
                  Send booking confirmation now
                </label>
              </div>
              <div className={styles.checkboxGroup}>
                <input
                  id="send-reminders"
                  type="checkbox"
                  checked={sendReminders}
                  onChange={(e) => setSendReminders(e.target.checked)}
                />
                <label htmlFor="send-reminders" className={styles.checkboxLabel}>
                  Send automatic reminder emails
                </label>
              </div>
            </fieldset>
          )}

          {step === 2 && showNotifyStep && session && (
            <fieldset className={styles.fieldGroup}>
              <legend className={styles.label}>Email notifications</legend>
              <div className={styles.checkboxGroup}>
                <input
                  id="send-reschedule-notification"
                  type="checkbox"
                  checked={sendRescheduleNotification}
                  onChange={(e) => setSendRescheduleNotification(e.target.checked)}
                />
                <label htmlFor="send-reschedule-notification" className={styles.checkboxLabel}>
                  Notify client of change by email
                </label>
              </div>
            </fieldset>
          )}

          {error && <p className={styles.error}>{error}</p>}
        </div>
      </Modal>
    );
  };

  return (
    <>
      {dynamicNewSessionModal()}
      {showDiscardConfirm && (
        <ConfirmModal
          title="Discard this session?"
          onClose={() => setShowDiscardConfirm(false)}
          onConfirm={onClose}
          confirmLabel="Yes, discard"
          cancelLabel="Keep editing"
        >
          <p>You have unsaved changes here. Closing now will lose them.</p>
        </ConfirmModal>
      )}
    </>
  );
};

export default CreateSessionModal;
