#!/usr/bin/env python3
"""Regenerate the compressed PDF cover-page image.

Reads the login art (public/pexels-amirali-shaghaghi-18428647.jpg), crops it to
A4 portrait ratio, blurs + darkens it to match the login screen's frosted panel,
and writes it as a ~10 KB base64 data URI into two twin modules:

  src/Helpers/pdfCoverImage.ts          (Vite app)
  supabase/functions/_shared/coverImage.ts   (edge functions)

Run after changing the login photo:  python scripts/build-pdf-cover.py
Needs Pillow:  python -m pip install Pillow
"""

import base64
import io
from pathlib import Path

from PIL import Image, ImageEnhance, ImageFilter

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "public" / "pexels-amirali-shaghaghi-18428647.jpg"
TARGET_RATIO = 1 / 1.414  # A4 portrait w:h
MAX_BYTES = 34_000


def build() -> str:
    img = Image.open(SRC).convert("RGB")
    w, h = img.size
    if w / h > TARGET_RATIO:
        new_w = int(h * TARGET_RATIO)
        x0 = (w - new_w) // 2
        img = img.crop((x0, 0, x0 + new_w, h))
    else:
        new_h = int(w / TARGET_RATIO)
        y0 = (h - new_h) // 2
        img = img.crop((0, y0, w, y0 + new_h))

    img = img.resize((720, int(720 / TARGET_RATIO)), Image.LANCZOS)
    img = img.filter(ImageFilter.GaussianBlur(6))
    img = ImageEnhance.Brightness(img).enhance(0.82)
    img = ImageEnhance.Color(img).enhance(0.9)

    data = None
    for quality in (42, 38, 34, 30):
        buf = io.BytesIO()
        img.save(buf, format="JPEG", quality=quality, optimize=True)
        data = buf.getvalue()
        if len(data) < MAX_BYTES:
            break
    return base64.b64encode(data).decode()


def main() -> None:
    uri = "data:image/jpeg;base64," + build()

    (ROOT / "src" / "Helpers" / "pdfCoverImage.ts").write_text(
        "// Auto-generated by scripts/build-pdf-cover.py — do not edit by hand.\n"
        "// Compressed + blurred crop of the login photo\n"
        '// (public/pexels-amirali-shaghaghi-18428647.jpg, "Amirali Shaghaghi" / Pexels),\n'
        "// ~10 KB, used as the cover-page backdrop for branded PDF exports.\n\n"
        f'export const PDF_COVER_JPEG =\n  "{uri}";\n',
        encoding="utf-8",
        newline="\n",
    )
    (ROOT / "supabase" / "functions" / "_shared" / "coverImage.ts").write_text(
        "// Auto-generated by scripts/build-pdf-cover.py — do not edit by hand.\n"
        "// Twin of src/Helpers/pdfCoverImage.ts; edge functions cannot import from the\n"
        "// Vite app, so the compressed cover image is duplicated here.\n\n"
        f'export const PDF_COVER_JPEG =\n  "{uri}";\n',
        encoding="utf-8",
        newline="\n",
    )
    print(f"cover image written, data URI {len(uri)} chars")


if __name__ == "__main__":
    main()
